spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false         # 실행되는 SQL을 콘솔에 출력 (개발용)
    defer-datasource-initialization: true

jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: ${ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}